name: Deploy Web API to Azure

on:
  workflow_dispatch:
  push:
    branches: 
      - 'release/**'
      
env:
  AZURE_WEBAPP_NAME: sharedhome
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
      
jobs:
  publish-webapi-to-azure:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
        
      - name: Restore dependencies
        run: dotnet restore API/src/SharedHome.Api
        
      - name: Build
        run: dotnet build --configuration Release API/src/SharedHome.Api

      - name: Publish
        run: dotnet publish API/src/SharedHome.Api --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'
        
      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
