name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs: 
  build:
    runs-on: ubuntu-latest
    
    environment:
      name: Test
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test_database
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3308:3306  
        options: >- 
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore API/src/SharedHome.Api
      
    - name: Build
      run: dotnet build --configuration Release API/src/SharedHome.Api
      
    - name: Run integration tests
      run: dotnet test --configuration Release API/tests/SharedHome.Domain.IntegrationTests
