name: Build and run integration tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  integration-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore API/src/SharedHome.Api
    - name: Build
      run: dotnet build --configuration Release API/src/SharedHome.Api
    - name: Run Integration Tests
      run: dotnet test --configuration Release API/tests/SharedHome.IntegrationTests
