name: Build and run tests

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore src/SharedHome.Api
    - name: Build
      run: dotnet build --configuration Release src/SharedHome.Api
    - name: Run Domain Tests
      run: dotnet test --configuration Release tests/SharedHome.Domain.UnitTests
    - name: Run Application Tests
      run: dotnet test --configuration Release tests/SharedHome.Applicatio.UnitTests
